satisfactory:
  planner:
    reload-profile:
      wipe: true
spring:
  neo4j:
    driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
    uri: bolt://${NEO4J_HOST}:${NEO4J_PORT}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher: DEBUG
factoryplanner:
  filestorage:
    url: ${FILE_STORAGE_URL}
    assets:
      accessKey: ${FILESTORE_ASSETS_ACCESS_KEY}
      secretKey: ${FILESTORE_ASSETS_SECRET_KEY}
    resources:
      accessKey: ${FILESTORE_RESOURCES_ACCESS_KEY}
      secretKey: ${FILESTORE_RESOURCES_SECRET_KEY}
