satisfactory:
  planner:
    reload-profile:
      wipe: true
        # Ignored when wipe is true
        #- RecipeTransformer
spring:
  neo4j:
    driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 5sS&v%^x5hxeglnq
logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher: ERROR
