satisfactory:
  planner:
    data:
      force-reload: true
spring:
  devtools:
    restart:
      enabled: true
      poll-interval: '5s'
      quiet-period: '1s'
      additional-paths:
        - src/main/kotlin
  neo4j:
    driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 5sS&v%^x5hxeglnq
