spring:
  neo4j:
    driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 5sS&v%^x5hxeglnq
logging:
  level:
    web: TRACE
    org:
      springframework:
        data:
          neo4j:
            cypher: DEBUG
springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html